config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :rooms, only: [:show,:index] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :room_id, presence: true
  validates :starts_at, :end_at, presence: true
  validates :user_id, presence: true
  validate :check_user_booking, on: :create
  
  def check_user_booking
    if Booking.where("user_id = ? AND starts_at <= ? AND end_at >= ?", user_id, end_at, starts_at).any?
      errors.add(:base, "You already have a booking in this date")
    end
  end

end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :name, :address, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  has_many :bookings, dependent: :destroy
  has_one_attached :photo


  validates :capacity, :price_per_night, :hotel, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :price_per_night, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def create
    @room = Room.find(params[:room_id]) # Assuming the room ID is available in the params
    @booking = current_user.bookings.build(booking_params.merge(room: @room))
    if @booking.save
      redirect_to room_path(params[:room_id]), notice: 'Booking was successfully created.'
    else
      flash.now[:alert] = @booking.errors.full_messages.join('. ').concat('.')
      redirect_to room_path(params[:room_id]), alert: "#{flash.now[:alert]}"
    end
  end

  def index
    @bookings = current_user.bookings
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
     @booking = Booking.find(params[:id])
      @booking.destroy
      redirect_to bookings_path, notice: 'Booking was successfully canceled.'
  end


  private

  def booking_params
    params.require(:booking).permit(:starts_at, :end_at)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
    if params[:query].present?
      # removes all digits from the address and compares it to the query
      sql_subquery = <<~SQL
      hotels.name ILIKE :query
      OR (regexp_replace(hotels.address, '\\d', '', 'g') ILIKE :query)
      OR rooms.price_per_night <= :query_integer
      SQL
      @rooms = Room.joins(:hotel).where(sql_subquery, query: "%#{params[:query]}%", query_integer: params[:query].to_i)
    else
      @rooms = Room.all
    end
  end

  def show
    @room = Room.find(params[:id])
    @booking = Booking.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div id="bookings" class="container">
  <div class="booking-container">
    <h3> Your bookings </h3>
    <%@bookings.each do |booking|%>
    <%nights = (booking.end_at.to_date - booking.starts_at.to_date).to_i %>
        <div class="booking-details">
            <h3><%= booking.room.hotel.name %></h3>
            <p><%= booking.starts_at.strftime("%d %b %Y") %> - <%= booking.end_at.strftime("%d %b %Y") %></p>
            <p><%= nights * booking.room.price_per_night %> MAD</p>
          <div class="booking-actions">
            <%= button_to "Cancel", booking_path(booking), method: :delete, turbo_confirm: "Are you sure?", class: "red-button" %>
          </div>
        </div>
    <%end%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBookRoomsChallenge</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="bg-image">
    <div class="site-desc">
      <h1>Book your next hotel room with us</h1>
      <p>Find the best hotel rooms at the best prices</p>
      <a href="<%= user_signed_in? ? rooms_path : new_user_session_path %>" class="btn btn-primary">Book now</a>
    </div>
  </div>

app/views/rooms/index.html.erb
<div id="index">
  <div class="search-bar">
  <%= form_tag rooms_path, :method => 'get' do %>
    <%= text_field_tag :query, params[:query], :placeholder => "Search by name, price or address", class: "search" %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>
</div>


<div class="rooms">
    <% @rooms.each do |room| %>
    <div class="room-card">
      <div class="room-image">
        <%= cl_image_tag room.photo.key%>
      </div>
      <div class="hotel">
        <h2><%= link_to room.hotel.name, room %></h2>
        <p><%= room.hotel.address %></p>
        <hr>
          <div class="infos">
            <p><i class="fa-solid fa-money-bill"></i></i> <%= room.price_per_night %> MAD / night</p>
            <p><i class="fa-solid fa-user"></i></i> <%= room.capacity %></p>
          </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div id="show">
  <%=link_to rooms_path do %>
    <i class="fa-solid fa-circle-arrow-left">Rooms</i>
  <%end%>
  <div class="room-details">
    <div class="room-image">
      <%= cl_image_tag @room.photo.key %>
    </div>
    <div class="room-infos">
      <div class="room-details-container">
        <div class="infos">
          <h2><%= @room.hotel.name %></h2>
          <div>
            <p><i class="fa-solid fa-money-bill"></i></i> <span id="price"><%= @room.price_per_night %></span> MAD</p>
            <p><i class="fa-solid fa-user"></i></i> <%= @room.capacity %></p>
          </div>
        </div>
        <hr>
        <p><%= @room.hotel.address %></p>
        <hr>
        <div class="reservation">
          <h2>Book this room</h2>
          <%# check in and check out date get extracted from the input field and saved to the hidden form sent to database %>
          <label for="date_range">Select Check-in and check-out date </label>
          <input type="text" id="date_range" class="flatpickr" data-controller="datepicker" readonly>
          <div id="nights" class="d-none">
            <p>Total Nights: <span id="totalNights"></span></p>
          </div>
          <div class="d-none" id="total">
            <p>Your total price is: <span id="total-price"></span>  MAD</p>
          </div>
        <%= form_with model: [@room, @booking] do |form| %>

          <%= form.hidden_field :starts_at, id: "starts_at" %>
          <%= form.hidden_field :end_at, id: "end_at" %>
          <%= form.submit "Book now", class: "btn btn-primary mt-2" %>
        <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Rooms", rooms_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/v1702409240/bkvj6jcaiuvcbisuifx9.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>